# Only lint our files, not upstream
# MD013: Line length — disabled (prose wraps naturally)
MD013: false
# MD033: Inline HTML — allow (tables etc.)
MD033: false
# MD041: First line should be top-level heading — already satisfied
