# Mavis module
#
# MAVIS definitions for Python, automatically generated from mavis.h
#

AV_A_ANON_INCOMING = 29
AV_A_ARRAYSIZE = 56
AV_A_AUTH_METHOD = 33
AV_A_CERTSUBJ = 44
AV_A_CHALLENGE = 51
AV_A_CLASS = 34
AV_A_COMMENT = 17
AV_A_CURRENT_MODULE = 55
AV_A_DBCERTSUBJ = 45
AV_A_DBPASSWORD = 36
AV_A_DIGEST_MD5_RSPAUTH = 35
AV_A_DIGEST_MD5_URI = 28
AV_A_DN = 5
AV_A_EMAIL = 23
AV_A_FTP_ANONYMOUS = 22
AV_A_GID = 10
AV_A_GIDS = 24
AV_A_HOME = 19
AV_A_IDENTITY_SOURCE = 37
AV_A_IPADDR = 14
AV_A_LIMIT = 11
AV_A_MAILCHECK_POST = 41
AV_A_MAILCHECK_PRE = 42
AV_A_MEMBEROF = 1
AV_A_PASSWORD = 8
AV_A_PASSWORD_MUSTCHANGE = 53
AV_A_PASSWORD_NEW = 50
AV_A_PASSWORD_ONESHOT = 52
AV_A_PATH = 7
AV_A_QUOTA_LIMIT = 15
AV_A_QUOTA_PATH = 16
AV_A_REALM = 27
AV_A_RESULT = 6
AV_A_ROOT = 20
AV_A_SCRAM_CLIENT_PROOF = 40
AV_A_SCRAM_SERVER_CHALLENGE = 38
AV_A_SCRAM_SERVER_PROOF = 39
AV_A_SERIAL = 21
AV_A_SERVERIP = 25
AV_A_SHELL = 54
AV_A_SSHKEY = 12
AV_A_SSHKEYHASH = 2
AV_A_SSHKEYID = 18
AV_A_TACCLIENT = 46
AV_A_TACMEMBER = 47
AV_A_TACPROFILE = 48
AV_A_TACTYPE = 49
AV_A_TARIFF = 26
AV_A_TIMESTAMP = 3
AV_A_TRAFFICSHAPING = 13
AV_A_TUNNEL = 43
AV_A_TYPE = 0
AV_A_UID = 9
AV_A_UMASK = 31
AV_A_USER = 4
AV_A_USER_RESPONSE = 32
AV_A_VHOST = 30
AV_V_AUTH_METHOD_APOP = "APOP"
AV_V_AUTH_METHOD_CRAM_MD5 = "CRAM-MD5"
AV_V_AUTH_METHOD_DIGEST_MD5 = "DIGEST-MD5"
AV_V_AUTH_METHOD_SCRAM_MD5 = "SCRAM-MD5"
AV_V_AUTH_METHOD_USER = "USER"
AV_V_BOOL_FALSE = "FALSE"
AV_V_BOOL_TRUE = "TRUE"
AV_V_RESULT_ERROR = "ERR"
AV_V_RESULT_FAIL = "NAK"
AV_V_RESULT_NOTFOUND = "NFD"
AV_V_RESULT_OK = "ACK"
AV_V_TACTYPE_AUTH = "AUTH"
AV_V_TACTYPE_CHAL = "CHAL"
AV_V_TACTYPE_CHPW = "CHPW"
AV_V_TACTYPE_INFO = "INFO"
AV_V_TRANSPORT_BOUNCE = "bounce"
AV_V_TRANSPORT_DEFER = "defer"
AV_V_TRANSPORT_FORWARD = "forward"
AV_V_TRANSPORT_LIST = "list"
AV_V_TRANSPORT_POP3 = "pop3"
AV_V_TRANSPORT_QUOTA_PERM = "quota-p"
AV_V_TRANSPORT_QUOTA_TEMP = "quota-t"
AV_V_TYPE_CANONICAL = "CANONICAL"
AV_V_TYPE_FTP = "FTP"
AV_V_TYPE_LOGIN = "LOGIN"
AV_V_TYPE_LOGSTATS = "PRIV_LOGSTATS"
AV_V_TYPE_POP3 = "POP3"
AV_V_TYPE_POP3PATH = "POP3PATH"
AV_V_TYPE_PRIVATE_PREFIX = "PRIV_"
AV_V_TYPE_PRIVATE_PREFIX_LEN = 5
AV_V_TYPE_RADIUS = "RADIUS"
AV_V_TYPE_TACPLUS = "TACPLUS"
AV_V_TYPE_TRANSPORT = "TRANSPORT"
AV_V_TYPE_VIRTUAL = "VIRTUAL"
AV_V_TYPE_WWW = "WWW"
MAVIS_API_VERSION = "5"
MAVIS_CONF_ERR = 1
MAVIS_CONF_OK = 0
MAVIS_DEFERRED = 1
MAVIS_DOWN = 16
MAVIS_FINAL = 0
MAVIS_FINAL_DEFERRED = 4
MAVIS_IGNORE = 2
MAVIS_INIT_ERR = 1
MAVIS_INIT_OK = 0
MAVIS_TIMEOUT = 3

import select, sys, os

os.environ["PYTHONUNBUFFERED"] = "1"

def write(av_pairs, result):
	for key in sorted(av_pairs):
		print(str(key) + " " + av_pairs[key])
	print("=" + str(result))

def read():
	av_pairs = { }
	while sys.stdin in select.select([sys.stdin], [], [], 0)[0]:
		line = sys.stdin.readline()
		if line:
			line = line.rstrip('\n')
			if line == "=":
				return av_pairs
			av_pair = line.split(" ")
			av_pairs[int(av_pair[0])] = av_pair[1]
		else:
			break
	exit(0)

