/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.2206 from the
 * contents of Scm.xs. Do not edit this file, edit Scm.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "Scm.xs"
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"
#include "mavis/scm.h"

#line 16 "Scm.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void S_croak_xs_usage(pTHX_ const CV * const cv, const char *const params);

STATIC void S_croak_xs_usage(pTHX_ const CV * const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
	const char *const gvname = GvNAME(gv);
	const HV *const stash = GvSTASH(gv);
	const char *const hvname = stash ? HvNAME(stash) : NULL;

	if (hvname)
	    Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
	else
	    Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
	/* Pants. I don't think that it should be possible to get here. */
	Perl_croak(aTHX_ "Usage: CODE(0x%" UVxf ")(%s)", PTR2UV(cv), params);
    }
}

#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)	S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage		S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif				/* !defined(newXS_flags) */

#line 68 "Scm.c"

XS(XS_Scm_scm_sendmsg);		/* prototype to pass -Wmissing-prototypes */
XS(XS_Scm_scm_sendmsg)
{
#ifdef dVAR
    dVAR;
    dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 3)
	croak_xs_usage(cv, "sock, type, fd");
    {
	int sock = (int) SvIV(ST(0));
	char *type = (char *) SvPV_nolen(ST(1));
	int fd = (int) SvIV(ST(2));
	int RETVAL;
	dXSTARG;
#line 16 "Scm.xs"
	struct scm_data sd;
	memset(&sd, 0, sizeof(sd));
	sd.type = type;
	RETVAL = scm_send_msg(sock, &sd, fd);
#line 91 "Scm.c"
	XSprePUSH;
	PUSHi((IV) RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Scm_scm_recvmsg);		/* prototype to pass -Wmissing-prototypes */
XS(XS_Scm_scm_recvmsg)
{
#ifdef dVAR
    dVAR;
    dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 3)
	croak_xs_usage(cv, "sock, type, fd");
    {
	int sock = (int) SvIV(ST(0));
	SV *type = ST(1);
	int fd = (int) SvIV(ST(2));
	int RETVAL;
	dXSTARG;
#line 29 "Scm.xs"
	char input[100];
	RETVAL = scm_recv_msg(sock, input, sizeof(input), &fd);
	if (!RETVAL)
	    sv_setpv(type, input);
#line 119 "Scm.c"
	ST(1) = type;
	SvSETMAGIC(ST(1));
	sv_setiv(ST(2), (IV) fd);
	SvSETMAGIC(ST(2));
	XSprePUSH;
	PUSHi((IV) RETVAL);
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
 XS(boot_Scm);			/* prototype to pass -Wmissing-prototypes */
XS(boot_Scm)
{
#ifdef dVAR
    dVAR;
    dXSARGS;
#else
    dXSARGS;
#endif
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char *file = __FILE__;
#else
    const char *file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv);	/* -W */
    PERL_UNUSED_VAR(items);	/* -W */
    XS_VERSION_BOOTCHECK;

    newXS("Scm::scm_sendmsg", XS_Scm_scm_sendmsg, file);
    newXS("Scm::scm_recvmsg", XS_Scm_scm_recvmsg, file);
#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
    if (PL_unitcheckav)
	call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}
